OneStop/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('weather/', include('weather.urls')),
    path('cal/',include('cal.urls')),
    path('todo/', include('todo.urls')),
    #path('/', include('cal.urls')),
]

cal/urls.py
from django.conf.urls import url
from . import views

app_name= 'cal'

urlpatterns=[
    #url(r'^$', views.index, name="home"),
    url(r'^index/$', views.CalendarView.as_view(), name='index'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
    url(r'^event/delete/(?P<event_id>\d+)/$', views.deleteEvent, name='event_delete'),
]

todo/urls.py
from django.conf.urls import url
from . import views

app_name= 'todo'
urlpatterns = [
    url(r'^$',views.index, name="index"),
    url(r'^update_task/(?P<pk>\w+)/$', views.updateTask, name="update_task"),
   url(r'^delete/(?P<pk>\w+)/$', views.deleteTask, name="delete_task"),

]

weather/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name='weather'

urlpatterns=[
    url(r'^$',views.index, name="index"),
    #url(r'^index/$', views.index, name='index'),
    
]

cal/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Event(models.Model):
    title=models.CharField(max_length=200)
    description=models.TextField()
    start_time=models.DateTimeField()
    end_time=models.DateTimeField()

    @property
    def get_html_url(self):
        url=reverse('cal:event_edit', args=(self.id,))
        return f'<a href="{url}">{self.title}</a>"'

todo/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    title= models.CharField(max_length=200)
    complete = models.BooleanField(default=False)
    created= models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    

weather/models.py
from django.db import models

# Create your models here.
class City(models.Model):
    name=models.CharField(max_length=25)

    def __str__(self): #show the actual city name on dashboard
        return self.name

    class Meta: #show the plural of city as cities instead of citys
        verbose_name_plural= 'cities'

cal/forms.py
from django.forms import ModelForm, DateInput
from cal.models import Event

class EventForm(ModelForm):
    class Meta:
        model= Event
        widgets={
            'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        fields= '__all__'

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['start_time'].input_formats=('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats=('%Y-%m-%dT%H:%M',)

    

todo/forms.py
from django import forms
from django.forms import ModelForm

from .models import *

class TaskForm(forms.ModelForm):

    title=forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Add a new task...'}))

    class Meta:
        model = Task #which model are we creating for the form for
        fields='__all__' # what fields are we going to allow in the form
    

weather/forms.py
from django.forms import ModelForm, TextInput
from .models import City

class CityForm(ModelForm):
    class Meta:
        model=City
        fields = ['name']
        widgets = {
            'name': TextInput(attrs={'class' : 'input', 'placeholder' : 'City Name'}),
        } #updates the input class to have the correct Bulma class and placeholder

cal/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from datetime import datetime
from datetime import timedelta
from datetime import date
import calendar
from django.views import generic
from django.utils.safestring import mark_safe
from django.urls import reverse

from .forms import EventForm
from .models import *
from .utils import Calendar


class CalendarView(generic.ListView):
    model=Event
    template_name='cal/calendar.html'

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)

        #d=get_date(self.request.GET.get('day',None))

        d=get_date(self.request.GET.get('month',None))
        cal=Calendar(d.year, d.month)

        html_cal=cal.formatmonth(withyear=True)
        context['calendar']=mark_safe(html_cal)
        context['prev_month']=prev_month(d)
        context['next_month']=next_month(d)

        return context

def get_date(req_day):
    if req_day:
        year, month= (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first=d.replace(day=1)
    prev_month=first-timedelta(days=1)
    month='month='+str(prev_month.year)+ '-'+str(prev_month.month)
    return month

def next_month(d):
    days_in_month=calendar.monthrange(d.year, d.month)[1]
    last=d.replace(day=days_in_month)
    next_month=last+ timedelta(days=1)
    month='month=' + str(next_month.year)+ '-'+ str(next_month.month)
    return month

def event(request, event_id=None):
    instance= Event()
    if event_id:
        instance= get_object_or_404(Event, pk=event_id)
    else:
        instance=Event()
    
    form=EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('cal:index'))
    context={'form': form, 'instance': instance}
    return render(request, 'cal/event.html', context)

def deleteEvent(request, event_id=None):
    instance=Event()
    if event_id:
        instance=Event.objects.get(id=event_id)

    if request.method=='POST':
        instance.delete()
        #return HttpResponseRedirect(reverse('cal:index'))
        return redirect('cal:index')

    context={'instance': instance}
    return render(request, 'cal/delete.html', context)

todo/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *
# Create your views here.

def index(request):
    tasks= Task.objects.all()

    form = TaskForm()

    if request.method =="POST":
        form=TaskForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('todo:index')


    context={'tasks': tasks, 'form': form}
    return render(request, 'todo/list.html', context)

def updateTask(request, pk):
    task=Task.objects.get(id=pk)

    form=TaskForm(instance= task)  #pre-fills the form for the instance

    if request.method=="POST":
        form=TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('todo:index')
    
    context= {'form': form}
    return render(request, 'todo/update_task.html', context)

def deleteTask(request, pk):
    item= Task.objects.get(id=pk)

    if request.method== 'POST':
        item.delete()
        return redirect('todo:index')

    context={'item': item}
    return render(request, 'todo/delete.html', context)

weather/views.py
from django.shortcuts import render
import requests
from .models import City
from decouple import config
from .forms import CityForm

# Create your views here.
def index(request):
    url = config('WEATHER_API_URL')
    cities=City.objects.all() #return all the cities in the database
    
    if request.method== 'POST':
        form = CityForm(request.POST) # add actual request data to form for processing
        form.save() # will validate and save if validate
    
    #city = 'Kolkata'
    form= CityForm()
    weather_data=[]

    for city in cities:
        city_weather = requests.get(url.format(city)).json() #request the API data and convert the JSON to Python data types

        weather = {
            'city' : city,
            'temperature' : city_weather['main']['temp'],
            'description' : city_weather['weather'][0]['description'],
            'icon' : city_weather['weather'][0]['icon']
        }
        weather_data.append(weather)

    context = {'weather_data' : weather_data, 'form': form}


    return render(request, 'weather/weather.html', context) #returns index.html template

cal/templates/cal/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}">
  <title>OneStop</title>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-field">
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>

                </button>
                <a class="navbar-brand" href="">OneStop</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">

                    <li class="">
                        <a href="{% url 'weather:index' %}">
                            Weather
                        </a>
                    </li>

                    <li class="nav-item active">
                        <a href="{% url 'cal:index' %}">
                            Calendar
                        </a> 

                    </li>

                    <li class="">
                        <a href="{% url 'todo:index' %}">
                            To-Do
                        </a> 
                    </li>

                </ul>
            </div>
        </div>
    </nav>
  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

cal/templates/cal/calendar.html
{% extends 'cal/base.html' %}

{% block content %}
<div class="clearfix">
    <a class=" btn btn-info left" href="{% url 'cal:index' %}?{{ prev_month }}">
        Previous Month
    </a>
    
    <a class="btn btn-info right" href="{% url 'cal:index' %}?{{ next_month }}">
        Next Month
    </a>
    <center>
    <a class="btn btn-info" href="{% url 'cal:event_new' %}">
        New Event
    </a>
    </center>

</div>
{{ calendar }}
{% endblock %}

cal/templates/cal/delete.html
{% extends 'cal/base.html' %}

{% block content %}
<center>
<p>Are you sure you want to delete "{{ instance.title }}" ?</p>

<form method="POST" >
    {% csrf_token %}
    <a class="btn btn-info" href="{% url 'cal:index' %}"> Cancel</a> 
    <input class="btn btn-info" type="submit" name="Confirm" value="Confirm">
</form>
</center>
{% endblock %}

cal/templates/cal/event.html
{% extends 'cal/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="center-column">
<center>
<div class="clearfix">
    <a class="btn btn-info left" href="{% url 'cal:index'%}"> Calendar</a>
</div>

<form method="post">
    {% csrf_token %}
    {% if instance.id %}
      <h3> Update Event </h3>
    {% else %}
      <h3> New Event </h3>
    {% endif %}
    <br>
    <table class="form form-table">
      {{ form }}
      
      <tr><td> &nbsp;</td></tr>
      <tr>
        <td>
        {% if instance.id %}
        <a class="btn btn-info right" href="{% url 'cal:event_delete' instance.id %}">Delete Event</a>
        {% endif %}
        </td>
        <td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td>
      </tr>
      
    </table>
  </form>
</center>
</div>
{% endblock %}

todo/templates/todo/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  <link rel="stylesheet" type="text/css" href="{% static 'todo/styles.css' %}">
  <title>OneStop</title>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-field">
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>

                </button>
                <a class="navbar-brand" href="">OneStop</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">

                    <li class="">
                        <a href="{% url 'weather:index' %}">
                            Weather
                        </a>
                    </li>

                    <li class="">
                        <a href="{% url 'cal:index' %}">
                            Calendar
                        </a> 

                    </li>

                    <li class="nav-item active">
                        <a href="{% url 'todo:index' %}">
                            To-Do
                        </a> 
                    </li>

                </ul>
            </div>
        </div>
    </nav>
  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

todo/templates/todo/delete.html
{% extends 'todo/base.html' %}

{% block content %}
<center>
<p>Are you sure you want to delete "{{ item }}" ?</p>

<form method="POST" >
    {% csrf_token %}
    <a class="btn btn-info create" href="{% url 'todo:index' %}"> Cancel</a> 
    <input class="btn btn-info create" type="submit" name="Confirm" value="Confirm">
</form>
</center>
{% endblock %}

todo/templates/todo/list.html
{% extends 'todo/base.html' %}

{% block content %}

<div class="center-column">
    <center>
    <h3> To Do List </h3>

    <form method="POST" action="{% url 'todo:index' %}" class="todo-form">
        {% csrf_token %}
        {{form.title}}
        <div class="submit">
        <input class="btn btn-info create" type="submit" name="Create" value="Create">
        </div>
    </form>
    
    <table>
    {% for task in tasks %}
        <tr>
        <div class="task">
            <td>
                {% if task.complete == True %}
                <strike> {{ task }}</strike>
                {% else %}
                <span> {{ task }} </span>
                {% endif %}
                </td>
            <td>
                <a class="btn btn-info" href="{% url 'todo:update_task' task.id %}">Update</a>
            </td>
            <td> 
                <a class="btn btn-danger" href="{% url 'todo:delete_task' task.id %}">Delete</a>
            </td>
            
        </div>
        </tr>
    {% endfor %}
    </table>
    </center>
</div>
{% endblock %}

todo/templates/todo/update_task.html
<h3>Update Task</h3>

<form method="POST" action="">
    {% csrf_token %}

    {{ form }}
    <input type="submit" name="Update Task" value="Update">
</form>

weather/templates/weather/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}OneStop{% endblock %}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'weather/styles.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-field">
                <!-- Header -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>

                    </button>
                    <a class="navbar-brand active" href="">OneStop</a>
                </div>

                <!-- Items -->
                <div class="collapse navbar-collapse" id="topNavBar">
                    <ul class="nav navbar-nav">

                        <li class="nav-item active">
                            <a href="{% url 'weather:index' %}">
                                Weather
                            </a>
                        </li>

                        <li class="nav-item ">
                            <a href="{% url 'cal:index' %}">
                                Calendar
                            </a> 
    
                        </li>
                        
                        <li class="nav-item">
                            <a href="{% url 'todo:index' %}">
                                To-Do
                            </a> 
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
    </body>
</html>

weather/templates/weather/weather.html
{% extends 'weather/base.html' %}

{% block content %}

<div class="center-column">
    <center>
        <h3> Weather </h3>
        <form method="POST">
            {% csrf_token %}
            {{ form.name }}
            <button class="btn btn-info">
                Add City
            </button>
        </form>
        <table>
            {% for weather in weather_data %}
                <tr><td>
                    <figure class="image is-50x50">
                        <img src="http://openweathermap.org/img/w/10d.png" alt="Image">
                    </figure>
                    <div class="content">
                        <p>
                            <span class="title">{{ weather.city }}</span>
                            <br>
                            <span class="subtitle">{{ weather.temperature }}° F</span>
                            <br> {{ weather.description }}
                        </p>
                    </div>
                </td></tr>
            {% endfor %}
        </table>
    </center>
</div>
{% endblock %}